name: gazoo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'


dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  location: ^4.2.0
  http: ^0.13.4
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.2.6
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_native_splash: ^2.2.18

flutter_native_splash:
  image:  assets/images/gazoo_logo.png
  background_image:  "assets/images/gazoo_background.png"
  


flutter: 
  uses-material-design: true
  assets:
    - assets/images/gazoo_logo.png
    - assets/images/userPosition.png
    - assets/images/bouteilleGaz.png
    - assets/images/listeDepots.png
    - assets/images/depotGaz.png
    - assets/images/depotGazMap.png
    - assets/images/whatsapp.png
    - assets/images/prix.png
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

