name: gazoo
version: 1.0.0+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  location: ^5.0.3
  http: ^1.2.0
  get_storage: ^2.1.1
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.6
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.18

flutter_native_splash:
  image: assets/images/gazoo_logo.png
  background_image: "assets/images/gazoo_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/gazoo_logo.png
    - assets/images/userPosition.png
    - assets/images/bouteilleGaz.png
    - assets/images/listeDepots.png
    - assets/images/depotGaz.png
    - assets/images/depotGazMap.png
    - assets/images/whatsapp.png
    - assets/images/prix.png
    - shorebird.yaml

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
